name: Android CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 18
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '18'

    # Instala o Gradle globalmente de forma limpa na máquina virtual
    - name: Setup Gradle Global CLI
      uses: gradle/actions/setup-gradle@v3

    # Gera a árvore do Wrapper original estruturando o Version Catalog (libs)
    - name: Generate local Gradle Wrapper
      run: gradle wrapper

    # Garante a permissão de execução nativa do script gerado
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Limpa o cache corrompido de tipos do Kotlin e compila o APK de uma só vez
    - name: Build and Assemble APK
      run: ./gradlew clean assembleDebug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        
